#!/usr/bin/env bash
# setup-env.sh
# Interactive builder for .env. Friendlier than editing the file by hand.
# Run from the repo root:  bash scripts/setup-env.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${REPO_DIR}/.env"
TPL="${REPO_DIR}/.env.example"

[[ -f "$TPL" ]] || { echo ".env.example missing"; exit 1; }

if [[ -f "$ENV_FILE" ]]; then
    read -r -p ".env already exists. Overwrite? [y/N] " ans
    [[ "$ans" =~ ^[Yy] ]] || { echo "Keeping existing .env"; exit 0; }
fi

ask() {
    local var="$1" prompt="$2" default="${3:-}" silent="${4:-no}"
    local val=""
    if [[ "$silent" == "yes" ]]; then
        read -r -s -p "  ${prompt}${default:+ [hidden]}: " val
        echo
    else
        read -r -p "  ${prompt}${default:+ [$default]}: " val
    fi
    echo "${var}=${val:-$default}"
}

echo
echo "===== Breaking News Agent - .env setup ====="
echo "(Press Enter to accept defaults. Leave blank to skip a platform.)"
echo

{
echo "# Generated by setup-env.sh on $(date -u +%FT%TZ)"
echo "LOG_LEVEL=INFO"
echo "DATABASE_URL=sqlite:///./data/agent.db"
echo "POLL_INTERVAL_SECONDS=60"
echo

echo "# ---- AI provider ----"
ask AI_PROVIDER          "AI provider (anthropic|openai)" "anthropic"
ask AI_MODEL             "AI model name" "claude-haiku-4-5-20251001"
ask ANTHROPIC_API_KEY    "Anthropic API key" "" yes
ask OPENAI_API_KEY       "OpenAI API key (optional)" "" yes
echo

echo "# ---- News sources ----"
ask RSS_FEEDS            "RSS feed URLs (comma-separated)" \
    "https://feeds.reuters.com/reuters/topNews,https://rss.cnn.com/rss/cnn_latest.rss"
ask NEWSAPI_KEY          "NewsAPI key (optional)" "" yes
echo

echo "# ---- X (Twitter) ----"
ask X_API_KEY            "X API key" "" yes
ask X_API_SECRET         "X API secret" "" yes
ask X_ACCESS_TOKEN       "X access token" "" yes
ask X_ACCESS_TOKEN_SECRET "X access token secret" "" yes
ask X_BEARER_TOKEN       "X bearer token" "" yes
echo

echo "# ---- Threads ----"
ask THREADS_ACCESS_TOKEN "Threads access token" "" yes
ask THREADS_USER_ID      "Threads user ID"
echo

echo "# ---- Telegram ----"
ask TELEGRAM_BOT_TOKEN   "Telegram bot token" "" yes
ask TELEGRAM_CHANNEL_ID  "Telegram channel @handle"
echo

echo "# ---- YouTube ----"
ask YOUTUBE_CLIENT_ID    "YouTube OAuth client id" "" yes
ask YOUTUBE_CLIENT_SECRET "YouTube OAuth client secret" "" yes
ask YOUTUBE_REFRESH_TOKEN "YouTube refresh token" "" yes
ask ELEVENLABS_API_KEY   "ElevenLabs key (TTS, optional)" "" yes
ask PEXELS_API_KEY       "Pexels key (stock footage, optional)" "" yes
echo

echo "# ---- Feature flags ----"
read -r -p "  Enable X? [y/N] " v;        echo "ENABLE_X=$([[ $v =~ ^[Yy] ]] && echo true || echo false)"
read -r -p "  Enable Threads? [y/N] " v;  echo "ENABLE_THREADS=$([[ $v =~ ^[Yy] ]] && echo true || echo false)"
read -r -p "  Enable Telegram? [Y/n] " v; echo "ENABLE_TELEGRAM=$([[ $v =~ ^[Nn] ]] && echo false || echo true)"
read -r -p "  Enable YouTube? [y/N] " v;  echo "ENABLE_YOUTUBE=$([[ $v =~ ^[Yy] ]] && echo true || echo false)"

read -r -p "  Live posting? (DRY_RUN=false) [y/N] " v
echo "DRY_RUN=$([[ $v =~ ^[Yy] ]] && echo false || echo true)"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo
echo "Wrote $ENV_FILE (chmod 600)"
echo "Next:  bash scripts/deploy.sh"
